name: Stock Report

on:

  workflow_dispatch:

  schedule:
    - cron: '0 9 * * 1-5'

jobs:

  run-stock-report:

    runs-on: ubuntu-latest

    steps:

      - name: 체크아웃
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 패키지 설치
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install finance-datareader
          pip install pykrx
          pip install openpyxl
          pip install beautifulsoup4
          pip install lxml
          pip install requests

      - name: 실행
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        run: |
          python stock_report.py
